### ISSUE TITLE
Trying to understand why data set is insane

### ISSUE THREAD

**Issue by maxwell-pung-bsi** [reallyreallyrandom/ent3000#3]
I am running ent3000 against a 1MB file generated from the conditioned output of a HRNG. To my surprise, the file failed the sanity check. Out of curiosity, I decided to comment out the code that exits the application when sanity check fails to get some better insight into why this data file is problematic. The output is shown below.
```text
ent3000 starting...
--help option to display this help.
Testing first 1000000 bytes.
Insane sample file. Bad.
Entropy,         p = 0.191,    PASS.  
Compression,     p = 0.641,    PASS.  
Chi,             p = 0.743,    PASS.  
Mean,            p = 0.002,    FAIL.  
Pi,              p = 0.039,    PASS.  
UnCorrelation,   p = 0.920,    PASS.  
------------------------------------
Finished.
```
What is the difference between the chi test performed in sanity check vs chi test that is performed later? I am surprised that the sanity's chi test failed but the regular one did not.

If interested, the data file I am passing ent3000 can be downloaded from MediaFire using [this](https://www.mediafire.com/file/j99r3l4plkjy65o/data.bin/file) link.

**Comment by reallyreallyrandom** [comment]
See Issue #2.  It could just be bad luck.  That happens statistically. Try again and get back, but make sure you use the latest source as of now.

**Comment by reallyreallyrandom** [comment]
I have to conclude that you were just unluck that day :-)

**Comment by maxwell-pung-bsi** [comment]
Got the latest code integrated into my fork and re-tested by running the data set through it 11 times. The results were
* 8 All passed
* 1 UnCorrelation failure
* 1 Pi failure
* 1 Chi failure
As you stated, the failure are expected to happen statistically so I think that explains what I am seeing.
